
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/server
hooks:
  ApplicationStart:
    - location: deploy/scripts/start_app.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
      - location: deploy/scripts/set-permissions.sh
